{
 "title": "Gateway Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Accepted Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gateway_accepted_events_total[1m]))"
    },
    {
     "expr": "sum(rate(ttk_accepted_events_total[1m]))"
    },
    {
     "expr": "sum(rate(fb_accepted_events_total[1m]))"
    }
   ]
  },
  {
   "title": "Processed Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gateway_processed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(ttk_processed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(fb_processed_events_total[1m]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gateway_failed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(ttk_failed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(fb_failed_events_total[1m]))"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(gateway_failed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(ttk_failed_events_total[1m]))"
    },
    {
     "expr": "sum(rate(fb_failed_events_total[1m]))"
    }
   ]
  },
  {
   "title": "Request Duration (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(reporter_request_duration_seconds_bucket[1m])) by (le, category))",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(reporter_request_count[1m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(reporter_error_count[1m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(reporter_error_count[1m])) by (category) / sum(rate(reporter_request_count[1m])) by (category) * 100",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}