FROM node:18-alpine

WORKDIR /app

# Copy package files and install only production dependencies
COPY package*.json ./
RUN npm install --production

# Copy the rest of your source code
COPY . .

# Build the NestJS app
RUN npm run build

# Expose the app port
EXPOSE 3001

# Start the app in production mode
CMD ["npm", "run", "start:prod:fb-collector"]
